-   id: stylelint
    name: stylelint
    description: ''
    entry: stylelint
    language: node
    'files': \.(css|scss|sass)$
    args: []
    require_serial: false
    additional_dependencies: ["stylelint@16.0.0-1"]
    minimum_pre_commit_version: '0'
